"use client"

import { Suspense, useLayoutEffect, useRef } from "react";
import DefaultScripts from "@/Components/Scripts";
export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}


export default async function PageLayout({
	children,
}: {
	children: React.ReactNode
}) {


	return (<>{children}
		<Suspense>
		<DefaultScripts/>
	</Suspense></>)}
